encoding:         utf-8
title:            Other
description:      Blog for recording the way of life.
#Your site's domain goes here. Leave localhost server or blank when working locally.
baseurl:          /other
url:              http://lendfating.github.com

# Owner/author information
owner:
  name:           Lendfating
  avatar:         /assets/images/avatar.jpg
  bio:            "I am a student majoring in computer science at UCAS now. And I will be graduating in 2016 summer."
  email:          lizhen00000@gmail.com
  # Social networking links used in footer. Update and remove as you like.
  github:         https://github.com/Lendfating
  linkedin:       http://www.linkedin.com/profile/view?id=352723424&authType=name&authToken=C1k5&trk=member-photo
  weibo:         http://www.weibo.com/Lendfating
  twitter:        https://twitter.com/Lendfating
  facebook:       https://www.facebook.com/lendfating
  # For Google Authorship https://plus.google.com/authorship
  google_plus:   https://plus.google.com/u/0/104389003870280325782/posts

# Analytics and webmaster tools stuff goes here
google_analytics:   UA-52550195-1
google_verify:      fZui8gemJWp_6GIGMGUgnF5l5o5b0RgzDhfmzv-PSnY

disqus_shortname: lendfating

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Asia/Beijing
future:      true
pygments:    true
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
# permalink:   /:categories/:title/ 带着会出现中文异常（对分类、中文文章名无法处理）

# Amount of post to show on home page
paginate: 10
paginate_path: "page:num"

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: true

  coderay:
    coderay_line_numbers: nil
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

source:      ../
destination: /workspace/lendfating.github.com/other
plugins:     ../_plugins
layouts:     ../_layouts
include: [".htaccess"]
exclude: [ "assets", "study", "_posts/study", "project", "_posts/project", "home.html", "publish.bat", "robots.txt"]
